/* ==========================================================================
   BELFIORE & CIRCELLI FAMILY DATA
   Structured registry for the interactive family tree canvas.
   Six generations, from San Bartolomeo in Galdo to Tampa, Florida.
   ========================================================================== */

const FAMILY_DATA = {
    rootPersonId: 'seb',

    people: [
        /* ===== GENERATION 0: Italian Origins ===== */
        {
            id: 'giuseppe_circelli',
            firstName: 'Giuseppe',
            lastName: 'Circelli',
            birthYear: null,
            deathYear: 1884,
            deathYearApprox: true,
            isLiving: false,
            primaryLocation: 'San Bartolomeo in Galdo, Italy',
            confidence: 'high',
            generation: 0,
            notes: "Maria Donata's father. Deceased by January 1884 (listed as 'fu' on daughter's marriage record).",
            source: '1884 marriage record (Act No. 16)'
        },
        {
            id: 'marianna_mita',
            firstName: 'Marianna',
            lastName: 'Mita',
            birthYear: null,
            deathYear: 1884,
            deathYearApprox: true,
            isLiving: false,
            primaryLocation: 'San Bartolomeo in Galdo, Italy',
            confidence: 'high',
            generation: 0,
            notes: "Maria Donata's mother. Deceased by 1884.",
            source: '1884 marriage record'
        },

        /* ===== GENERATION 1: Immigrants ===== */
        {
            id: 'leonardantonio',
            firstName: 'Leonardantonio',
            lastName: 'Belfiore',
            aka: 'Anthony / Antonio Belfiore',
            birthYear: 1857,
            birthYearApprox: true,
            deathYear: 1938,
            isLiving: false,
            primaryLocation: 'New Rochelle, NY',
            confidence: 'verified',
            generation: 1,
            notes: "Foundling (padre ignoto, madre ignota). 'Belfiore' was an institutionally assigned surname — bel fiore, 'beautiful flower.' Patriarch. Farmer. Illiterate. Immigrated to America and naturalized.",
            source: '1884 marriage record; Michael Belfiore death certificate'
        },
        {
            id: 'maria_donata',
            firstName: 'Maria Donata',
            lastName: 'Circelli',
            aka: 'Maria Doreta / Mary Belfiore',
            birthYear: 1862,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'New Rochelle, NY',
            confidence: 'verified',
            generation: 1,
            notes: "Matriarch. Arrived New York on S.S. Oregon, December 2, 1896, traveling under maiden name 'Circelli, Maria Doreta.'",
            source: 'S.S. Oregon ship manifest (1896); 1884 marriage record'
        },
        {
            id: 'salvatore_circelli',
            firstName: 'Salvatore',
            lastName: 'Circelli',
            birthYear: 1874,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'San Bartolomeo in Galdo, Italy',
            confidence: 'estimated',
            generation: 1,
            notes: "Likely brother or nephew of Maria Donata. Arrived March 1898 on S.S. Alsatia with Michele Circelli.",
            source: 'S.S. Alsatia manifest (1898); S.S. Sant\'Anna (1911)'
        },
        {
            id: 'michele_circelli',
            firstName: 'Michele',
            lastName: 'Circelli',
            birthYear: 1874,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'San Bartolomeo in Galdo, Italy',
            confidence: 'estimated',
            generation: 1,
            notes: "Likely brother or nephew of Maria Donata. NOT the same person as Michael Belfiore.",
            source: 'S.S. Alsatia manifest (1898)'
        },

        /* ===== GENERATION 2: The Nine Children ===== */
        {
            id: 'michael_kirtus',
            firstName: 'Michael Kirtus',
            lastName: 'Belfiore',
            birthYear: 1885,
            deathYear: 1952,
            isLiving: false,
            primaryLocation: '46 Mechanic St, New Rochelle, NY',
            confidence: 'verified',
            generation: 2,
            notes: "Seb's great-grandfather. The 'non-golfing brother.' House painter. Born in Italy, arrived as a child. Married twice.",
            source: 'Death certificate; WWI/WWII draft cards; 1940 Census'
        },
        {
            id: 'first_wife_michael',
            firstName: 'First Wife',
            lastName: '(Unknown)',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Bridgeport, CT area',
            confidence: 'low',
            generation: 2,
            notes: "Michael's first wife and mother of Dorothy. Name unknown. Marriage likely ended ~1918-1920.",
            source: 'Inferred from Michael\'s 1918 draft card listing Dorothy'
        },
        {
            id: 'frances_towey',
            firstName: 'Frances',
            lastName: 'Towey',
            birthYear: 1898,
            birthYearApprox: true,
            deathYear: 1967,
            isLiving: false,
            primaryLocation: 'New Rochelle, NY',
            confidence: 'verified',
            generation: 2,
            notes: "Irish-American. Michael's second wife. Towey surname from County Mayo/Roscommon. Seb's great-grandmother.",
            source: '1940 Census; NY State death records'
        },
        {
            id: 'sammy',
            firstName: 'Sammy',
            lastName: 'Belfore',
            aka: 'Samuel Belfiore Sr.',
            birthYear: 1899,
            deathYear: 1971,
            deathYearApprox: true,
            isLiving: false,
            primaryLocation: 'Daytona Beach, FL',
            confidence: 'verified',
            generation: 2,
            notes: "Born Christmas Day 1899. PGA professional. Pro-manager at Seabreeze Golf & Tennis Club. One PGA Tour win (1930). Coached blind golfer Clinton Russell.",
            source: 'New Rochelle Standard Star obituary; PGA Tour profile'
        },
        {
            id: 'virginia_hupp',
            firstName: 'Virginia',
            lastName: 'Hupp',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Birmingham, MI',
            confidence: 'high',
            generation: 2,
            notes: "Connected to the Hupp Motor Car Company (Hupmobile). Married Sammy ~1930, divorced ~1939. Later married John Moss.",
            source: 'Newspaper engagement announcement (1930); Patricia\'s obituary'
        },
        {
            id: 'frank',
            firstName: 'Frank',
            lastName: 'Belfore',
            aka: 'Francesco Belfiore',
            birthYear: 1897,
            birthYearApprox: true,
            deathYear: 1968,
            isLiving: false,
            primaryLocation: 'Daytona Beach, FL',
            confidence: 'verified',
            generation: 2,
            notes: "PGA professional. Ran the golf shop at Seabreeze Golf & Tennis Club alongside brother Sammy.",
            source: 'Sammy\'s obituary; Ancestry indexed records'
        },
        {
            id: 'joseph_golfer',
            firstName: 'Joseph',
            lastName: 'Belfore',
            aka: 'Joe Sr. — The Golfer',
            birthYear: 1895,
            birthYearApprox: true,
            deathYear: 1963,
            isLiving: false,
            primaryLocation: 'Grosse Pointe, MI',
            confidence: 'verified',
            generation: 2,
            notes: "Head pro at Country Club of Detroit. Michigan PGA Champion (1933, 1937). Michigan PGA President (1959-60). Authored 'Golfing Aids' (1940). NOT Seb's grandfather.",
            source: 'Michigan PGA Centennial; CCD Board Minutes (1963); NYT 1927'
        },
        {
            id: 'ruth',
            firstName: 'Ruth',
            lastName: 'Belfore',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Grosse Pointe, MI',
            confidence: 'estimated',
            generation: 2,
            notes: "Joe Sr.'s wife. Surname unknown. Mother of David and Jeffery.",
            source: 'CCD Board Minutes (1963)'
        },
        {
            id: 'rose',
            firstName: 'Rose',
            lastName: 'Belfiore',
            birthYear: 1903,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Wykagyl Gardens, New Rochelle, NY',
            confidence: 'high',
            generation: 2,
            notes: "Never married. Lived with sister Caroline at Wykagyl Gardens.",
            source: 'Sammy\'s obituary'
        },
        {
            id: 'caroline',
            firstName: 'Caroline',
            lastName: 'Belfiore',
            birthYear: 1903,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Wykagyl Gardens, New Rochelle, NY',
            confidence: 'high',
            generation: 2,
            notes: "Never married. Lived with sister Rose. May be the same person as 'Lena Belfiore' from 1901 census.",
            source: 'Sammy\'s obituary'
        },
        {
            id: 'mollie',
            firstName: 'Mollie',
            lastName: 'Drew',
            aka: 'née Belfiore',
            birthYear: 1900,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Davenport Ave, New Rochelle, NY',
            confidence: 'high',
            generation: 2,
            notes: "Sister. Married Anthony Drew.",
            source: 'Sammy\'s obituary'
        },
        {
            id: 'anthony_drew',
            firstName: 'Anthony',
            lastName: 'Drew',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'New Rochelle, NY',
            confidence: 'estimated',
            generation: 2,
            notes: "Mollie's husband.",
            source: 'Sammy\'s obituary'
        },
        {
            id: 'phyl',
            firstName: 'Phyl',
            lastName: 'Paternostro',
            aka: 'née Belfiore (Phyllis / Filomena)',
            birthYear: 1900,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Hartford, CT',
            confidence: 'high',
            generation: 2,
            notes: "Sister. Married Angelo Paternostro.",
            source: 'Sammy\'s obituary'
        },
        {
            id: 'angelo_paternostro',
            firstName: 'Angelo',
            lastName: 'Paternostro',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Hartford, CT',
            confidence: 'estimated',
            generation: 2,
            notes: "Phyl's husband.",
            source: 'Sammy\'s obituary'
        },
        {
            id: 'mary',
            firstName: 'Mary',
            lastName: 'D\'Onofrio',
            aka: 'née Belfiore',
            birthYear: 1900,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Hollywood, FL',
            confidence: 'high',
            generation: 2,
            notes: "Sister. Married Joseph D'Onofrio.",
            source: 'Sammy\'s obituary'
        },
        {
            id: 'joseph_donofrio',
            firstName: 'Joseph',
            lastName: 'D\'Onofrio',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Hollywood, FL',
            confidence: 'estimated',
            generation: 2,
            notes: "Mary's husband.",
            source: 'Sammy\'s obituary'
        },

        /* ===== GENERATION 3 ===== */
        {
            id: 'dorothy_first',
            firstName: 'Dorothy',
            lastName: 'Belfiore',
            birthYear: 1914,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'Bridgeport, CT',
            confidence: 'low',
            generation: 3,
            notes: "Michael's daughter from his FIRST marriage. Vanishes from records after 1918. NOT the same as Dorothy Hennessey.",
            source: 'Michael\'s 1918 WWI draft card'
        },
        {
            id: 'edward',
            firstName: 'Edward',
            lastName: 'Belfiore',
            birthYear: 1923,
            birthYearApprox: true,
            deathYear: null,
            isLiving: false,
            primaryLocation: '46 Mechanic St, New Rochelle, NY',
            confidence: 'high',
            generation: 3,
            notes: "Michael and Frances's son. Seb's great-uncle. Little known after 1940 census.",
            source: '1940 U.S. Census'
        },
        {
            id: 'joseph_grandfather',
            firstName: 'Joseph',
            lastName: 'Belfiore',
            aka: "Seb's Grandfather",
            birthYear: 1928,
            birthYearApprox: true,
            deathYear: 1986,
            isLiving: false,
            primaryLocation: 'Valrico, FL',
            confidence: 'verified',
            generation: 3,
            notes: "Seb's grandfather. Michael and Frances's son. Named after his uncle Joe the golfer. NOT the Michigan PGA President.",
            source: 'SSDI; 1940 Census; family knowledge'
        },
        {
            id: 'dorothy_hennessey',
            firstName: 'Dorothy',
            lastName: 'Belfiore',
            aka: 'née Hennessey',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'New Rochelle, NY',
            confidence: 'high',
            generation: 3,
            notes: "Seb's grandmother. Irish-American. Maiden name Hennessey. Joseph's wife.",
            source: 'Family knowledge'
        },
        {
            id: 'sammy_jr',
            firstName: 'Samuel M.',
            lastName: 'Belfore Jr.',
            birthYear: 1935,
            birthYearApprox: true,
            deathYear: 2025,
            deathYearApprox: true,
            isLiving: false,
            primaryLocation: 'Ormond Beach, FL',
            confidence: 'high',
            generation: 3,
            notes: "Sammy Sr.'s son. Died ~late 2024 / early 2025.",
            source: 'Sammy Sr.\'s obituary; Volusia County records'
        },
        {
            id: 'julia_belfore',
            firstName: 'Julia Clair',
            lastName: 'Belfore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Ormond Beach, FL',
            confidence: 'high',
            generation: 3,
            notes: "Sammy Jr.'s wife.",
            source: 'Volusia County property records (2025)'
        },
        {
            id: 'patricia',
            firstName: 'Patricia Hupp',
            lastName: 'Fleming',
            aka: 'née Belfore',
            birthYear: 1933,
            deathYear: 2022,
            isLiving: false,
            primaryLocation: 'Atlantis, FL',
            confidence: 'verified',
            generation: 3,
            notes: "Sammy Sr.'s daughter. English & theater teacher. Family story: nearly cast as Bonnie Butler in Gone with the Wind.",
            source: 'Obituary (Desmond Funeral Home)'
        },
        {
            id: 'john_fleming',
            firstName: 'John',
            lastName: 'Fleming',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Michigan / Florida',
            confidence: 'high',
            generation: 3,
            notes: "Patricia's husband. Real estate appraiser. Married 1958, divorced 1990 but remained friendly.",
            source: 'Patricia\'s obituary'
        },
        {
            id: 'david_belfore',
            firstName: 'David',
            lastName: 'Belfore',
            birthYear: 1936,
            deathYear: null,
            isLiving: true,
            primaryLocation: '679 Neff Rd, Grosse Pointe, MI',
            confidence: 'verified',
            generation: 3,
            notes: "Son of Joe Sr. (the golfer). Granted CCD golfing privileges after his father's death (1963). Second wife Judith died 2023.",
            source: 'Grosse Pointe News; CCD Board Minutes'
        },
        {
            id: 'judith_sattelmeier',
            firstName: 'Judith Ann',
            lastName: 'Sattelmeier',
            birthYear: null,
            deathYear: 2023,
            isLiving: false,
            primaryLocation: 'Grosse Pointe, MI',
            confidence: 'high',
            generation: 3,
            notes: "David Belfore's second wife. Died November 3, 2023.",
            source: 'Grosse Pointe News obituary'
        },
        {
            id: 'jeffery',
            firstName: 'Joseph F. "Jeffery"',
            lastName: 'Belfore Jr.',
            birthYear: 1917,
            deathYear: 1982,
            deathYearApprox: true,
            isLiving: false,
            primaryLocation: 'Possibly Vermont',
            confidence: 'estimated',
            generation: 3,
            notes: "Son of Joe Sr. (the golfer). Nicknamed 'Jeffery.' Middle initial 'F.' possibly stands for 'Frank' after his uncle.",
            source: 'CCD Board Minutes; tentative VT death records'
        },

        /* ===== GENERATION 4 ===== */
        {
            id: 'robert',
            firstName: 'Robert',
            lastName: 'Belfiore',
            aka: "Seb's Father",
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 4,
            notes: "Seb's father. Holds UK and US citizenship. Son of Joseph and Dorothy Hennessey Belfiore.",
            source: 'Family knowledge'
        },
        {
            id: 'william',
            firstName: 'William',
            lastName: 'Belfiore',
            aka: "Seb's Uncle",
            birthYear: 1950,
            birthYearApprox: true,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'high',
            generation: 4,
            notes: "Seb's uncle. Was 'not even 2 years old' when Michael died in January 1952. Provided Michael's death certificate and Sammy's obituary for this research.",
            source: 'Family knowledge'
        },
        {
            id: 'lisa_fleming',
            firstName: 'Lisa',
            lastName: 'Fleming',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'high',
            generation: 4,
            notes: "Daughter of Patricia Hupp Fleming. Married to Steve.",
            source: 'Patricia\'s obituary'
        },
        {
            id: 'chris_fleming',
            firstName: 'Chris',
            lastName: 'Fleming',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'high',
            generation: 4,
            notes: "Son of Patricia Hupp Fleming.",
            source: 'Patricia\'s obituary'
        },
        {
            id: 'john_fleming_jr',
            firstName: 'John',
            lastName: 'Fleming Jr.',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'high',
            generation: 4,
            notes: "Son of Patricia Hupp Fleming.",
            source: 'Patricia\'s obituary'
        },
        {
            id: 'geoff_fleming',
            firstName: 'Geoff',
            lastName: 'Fleming',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'high',
            generation: 4,
            notes: "Son of Patricia Hupp Fleming.",
            source: 'Patricia\'s obituary'
        },
        {
            id: 'barb_belfore',
            firstName: 'Barb',
            lastName: 'Hartman',
            aka: 'née Belfore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Grosse Pointe, MI',
            confidence: 'high',
            generation: 4,
            notes: "Daughter of David Belfore. Married John Hartman.",
            source: 'Judith Sattelmeier obituary'
        },
        {
            id: 'gary_belfore',
            firstName: 'Gary',
            lastName: 'Belfore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Grosse Pointe, MI',
            confidence: 'high',
            generation: 4,
            notes: "Son of David Belfore. Married to Jessica.",
            source: 'Judith Sattelmeier obituary'
        },
        {
            id: 'jill_belfore',
            firstName: 'Jill',
            lastName: 'Pappas',
            aka: 'née Belfore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Grosse Pointe, MI',
            confidence: 'high',
            generation: 4,
            notes: "Daughter of David Belfore. Married Chuck Pappas.",
            source: 'Judith Sattelmeier obituary'
        },

        {
            id: 'beth',
            firstName: 'Beth',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'verified',
            generation: 4,
            notes: "Daughter of Joseph and Dorothy Hennessey Belfiore. Sister of Robert, William, and Karen.",
            source: 'Family knowledge'
        },
        {
            id: 'karen',
            firstName: 'Karen',
            lastName: 'Carpenter',
            aka: 'née Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'verified',
            generation: 4,
            notes: "Daughter of Joseph and Dorothy Hennessey Belfiore. Sister of Robert, William, and Beth. Married Bill Carpenter.",
            source: 'Family knowledge'
        },
        {
            id: 'bill_carpenter',
            firstName: 'Bill',
            lastName: 'Carpenter',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'verified',
            generation: 4,
            notes: "Karen's husband.",
            source: 'Family knowledge'
        },
        {
            id: 'susan',
            firstName: 'Susan',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 4,
            notes: "William's wife. Mother of Loredana, Dani, Ionel, Ramona, Michaela, and Aidan.",
            source: 'Family knowledge'
        },
        {
            id: 'lena',
            firstName: 'Lena',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: false,
            primaryLocation: 'New Rochelle, NY',
            confidence: 'estimated',
            generation: 2,
            notes: "Appears in 1940 Census. May be a nickname for one of the known sisters (Caroline or Rose).",
            source: '1940 Census'
        },

        /* ===== GENERATION 5 ===== */
        {
            id: 'seb',
            firstName: 'Seb',
            lastName: 'Belfiore',
            birthYear: 1989,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Tampa, FL',
            confidence: 'verified',
            generation: 5,
            notes: "The researcher. 5th generation from the Italian immigrants. Product designer. Dual UK/US citizenship. Lives on Davis Island, Tampa.",
            source: 'Self'
        },
        {
            id: 'valeria',
            firstName: 'Valeria',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Tampa, FL',
            confidence: 'verified',
            generation: 5,
            notes: "Seb's wife. German. Mother of Enzo.",
            source: 'Family knowledge'
        },
        {
            id: 'alexander',
            firstName: 'Alexander',
            lastName: 'Belfiore',
            birthYear: 1989,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'verified',
            generation: 5,
            notes: "Seb's brother. Robert's son.",
            source: 'Family knowledge'
        },
        {
            id: 'lauren',
            firstName: 'Lauren',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'verified',
            generation: 5,
            notes: "Alexander's wife.",
            source: 'Family knowledge'
        },
        {
            id: 'christian_carpenter',
            firstName: 'Christian',
            lastName: 'Carpenter',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'verified',
            generation: 5,
            notes: "Son of Karen and Bill Carpenter.",
            source: 'Family knowledge'
        },
        {
            id: 'loredana',
            firstName: 'Loredana',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 5,
            notes: "Daughter of William and Susan Belfiore.",
            source: 'Family knowledge'
        },
        {
            id: 'dani',
            firstName: 'Dani',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 5,
            notes: "Child of William and Susan Belfiore.",
            source: 'Family knowledge'
        },
        {
            id: 'ionel',
            firstName: 'Ionel',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 5,
            notes: "Child of William and Susan Belfiore.",
            source: 'Family knowledge'
        },
        {
            id: 'ramona',
            firstName: 'Ramona',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 5,
            notes: "Daughter of William and Susan Belfiore.",
            source: 'Family knowledge'
        },
        {
            id: 'michaela',
            firstName: 'Michaela',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 5,
            notes: "Daughter of William and Susan Belfiore.",
            source: 'Family knowledge'
        },
        {
            id: 'aidan',
            firstName: 'Aidan',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'New Rochelle area',
            confidence: 'verified',
            generation: 5,
            notes: "Child of William and Susan Belfiore.",
            source: 'Family knowledge'
        },

        /* ===== GENERATION 6 ===== */
        {
            id: 'enzo',
            firstName: 'Enzo',
            lastName: 'Belfiore',
            birthYear: 2026,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'Tampa, FL',
            confidence: 'verified',
            generation: 6,
            notes: "6th generation from the Italian immigrants. Born January 2026 to Seb and Valeria. Triple citizenship: US, UK, German.",
            source: 'Family knowledge'
        },
        {
            id: 'violet',
            firstName: 'Violet',
            lastName: 'Belfiore',
            birthYear: null,
            deathYear: null,
            isLiving: true,
            primaryLocation: 'USA',
            confidence: 'verified',
            generation: 6,
            notes: "Daughter of Alexander and Lauren Belfiore. Enzo's cousin.",
            source: 'Family knowledge'
        }
    ],

    relationships: [
        /* ===== Spouse relationships ===== */
        { type: 'spouse', fromPersonId: 'giuseppe_circelli', toPersonId: 'marianna_mita' },
        { type: 'spouse', fromPersonId: 'leonardantonio', toPersonId: 'maria_donata', startYear: 1884 },
        { type: 'spouse', fromPersonId: 'michael_kirtus', toPersonId: 'first_wife_michael' },
        { type: 'spouse', fromPersonId: 'michael_kirtus', toPersonId: 'frances_towey' },
        { type: 'spouse', fromPersonId: 'sammy', toPersonId: 'virginia_hupp' },
        { type: 'spouse', fromPersonId: 'joseph_golfer', toPersonId: 'ruth' },
        { type: 'spouse', fromPersonId: 'mollie', toPersonId: 'anthony_drew' },
        { type: 'spouse', fromPersonId: 'phyl', toPersonId: 'angelo_paternostro' },
        { type: 'spouse', fromPersonId: 'mary', toPersonId: 'joseph_donofrio' },
        { type: 'spouse', fromPersonId: 'joseph_grandfather', toPersonId: 'dorothy_hennessey' },
        { type: 'spouse', fromPersonId: 'sammy_jr', toPersonId: 'julia_belfore' },
        { type: 'spouse', fromPersonId: 'patricia', toPersonId: 'john_fleming', startYear: 1958, endYear: 1990 },
        { type: 'spouse', fromPersonId: 'david_belfore', toPersonId: 'judith_sattelmeier' },
        { type: 'spouse', fromPersonId: 'seb', toPersonId: 'valeria' },
        { type: 'spouse', fromPersonId: 'karen', toPersonId: 'bill_carpenter' },
        { type: 'spouse', fromPersonId: 'william', toPersonId: 'susan' },
        { type: 'spouse', fromPersonId: 'alexander', toPersonId: 'lauren' },

        /* ===== Parent-child relationships ===== */
        // Giuseppe & Marianna -> Maria Donata
        { type: 'parent_child', fromPersonId: 'giuseppe_circelli', toPersonId: 'maria_donata' },
        { type: 'parent_child', fromPersonId: 'marianna_mita', toPersonId: 'maria_donata' },

        // Leonardantonio & Maria -> 9 children
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'michael_kirtus' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'michael_kirtus' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'sammy' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'sammy' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'frank' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'frank' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'joseph_golfer' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'joseph_golfer' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'rose' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'rose' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'caroline' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'caroline' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'mollie' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'mollie' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'phyl' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'phyl' },
        { type: 'parent_child', fromPersonId: 'leonardantonio', toPersonId: 'mary' },
        { type: 'parent_child', fromPersonId: 'maria_donata', toPersonId: 'mary' },

        // Michael -> Dorothy (first wife)
        { type: 'parent_child', fromPersonId: 'michael_kirtus', toPersonId: 'dorothy_first' },
        { type: 'parent_child', fromPersonId: 'first_wife_michael', toPersonId: 'dorothy_first' },

        // Michael & Frances -> Edward, Joseph
        { type: 'parent_child', fromPersonId: 'michael_kirtus', toPersonId: 'edward' },
        { type: 'parent_child', fromPersonId: 'frances_towey', toPersonId: 'edward' },
        { type: 'parent_child', fromPersonId: 'michael_kirtus', toPersonId: 'joseph_grandfather' },
        { type: 'parent_child', fromPersonId: 'frances_towey', toPersonId: 'joseph_grandfather' },

        // Sammy & Virginia -> Sammy Jr, Patricia
        { type: 'parent_child', fromPersonId: 'sammy', toPersonId: 'sammy_jr' },
        { type: 'parent_child', fromPersonId: 'virginia_hupp', toPersonId: 'sammy_jr' },
        { type: 'parent_child', fromPersonId: 'sammy', toPersonId: 'patricia' },
        { type: 'parent_child', fromPersonId: 'virginia_hupp', toPersonId: 'patricia' },

        // Joe Golfer & Ruth -> David, Jeffery
        { type: 'parent_child', fromPersonId: 'joseph_golfer', toPersonId: 'david_belfore' },
        { type: 'parent_child', fromPersonId: 'ruth', toPersonId: 'david_belfore' },
        { type: 'parent_child', fromPersonId: 'joseph_golfer', toPersonId: 'jeffery' },
        { type: 'parent_child', fromPersonId: 'ruth', toPersonId: 'jeffery' },

        // Joseph (grandfather) & Dorothy Hennessey -> Robert, William, Beth, Karen
        { type: 'parent_child', fromPersonId: 'joseph_grandfather', toPersonId: 'robert' },
        { type: 'parent_child', fromPersonId: 'dorothy_hennessey', toPersonId: 'robert' },
        { type: 'parent_child', fromPersonId: 'joseph_grandfather', toPersonId: 'william' },
        { type: 'parent_child', fromPersonId: 'dorothy_hennessey', toPersonId: 'william' },
        { type: 'parent_child', fromPersonId: 'joseph_grandfather', toPersonId: 'beth' },
        { type: 'parent_child', fromPersonId: 'dorothy_hennessey', toPersonId: 'beth' },
        { type: 'parent_child', fromPersonId: 'joseph_grandfather', toPersonId: 'karen' },
        { type: 'parent_child', fromPersonId: 'dorothy_hennessey', toPersonId: 'karen' },

        // Patricia & John -> Fleming kids
        { type: 'parent_child', fromPersonId: 'patricia', toPersonId: 'lisa_fleming' },
        { type: 'parent_child', fromPersonId: 'john_fleming', toPersonId: 'lisa_fleming' },
        { type: 'parent_child', fromPersonId: 'patricia', toPersonId: 'chris_fleming' },
        { type: 'parent_child', fromPersonId: 'john_fleming', toPersonId: 'chris_fleming' },
        { type: 'parent_child', fromPersonId: 'patricia', toPersonId: 'john_fleming_jr' },
        { type: 'parent_child', fromPersonId: 'john_fleming', toPersonId: 'john_fleming_jr' },
        { type: 'parent_child', fromPersonId: 'patricia', toPersonId: 'geoff_fleming' },
        { type: 'parent_child', fromPersonId: 'john_fleming', toPersonId: 'geoff_fleming' },

        // David -> Barb, Gary, Jill
        { type: 'parent_child', fromPersonId: 'david_belfore', toPersonId: 'barb_belfore' },
        { type: 'parent_child', fromPersonId: 'david_belfore', toPersonId: 'gary_belfore' },
        { type: 'parent_child', fromPersonId: 'david_belfore', toPersonId: 'jill_belfore' },

        // Robert -> Seb, Alexander
        { type: 'parent_child', fromPersonId: 'robert', toPersonId: 'seb' },
        { type: 'parent_child', fromPersonId: 'robert', toPersonId: 'alexander' },

        // Karen & Bill -> Christian
        { type: 'parent_child', fromPersonId: 'karen', toPersonId: 'christian_carpenter' },
        { type: 'parent_child', fromPersonId: 'bill_carpenter', toPersonId: 'christian_carpenter' },

        // William & Susan -> Loredana, Dani, Ionel, Ramona, Michaela, Aidan
        { type: 'parent_child', fromPersonId: 'william', toPersonId: 'loredana' },
        { type: 'parent_child', fromPersonId: 'susan', toPersonId: 'loredana' },
        { type: 'parent_child', fromPersonId: 'william', toPersonId: 'dani' },
        { type: 'parent_child', fromPersonId: 'susan', toPersonId: 'dani' },
        { type: 'parent_child', fromPersonId: 'william', toPersonId: 'ionel' },
        { type: 'parent_child', fromPersonId: 'susan', toPersonId: 'ionel' },
        { type: 'parent_child', fromPersonId: 'william', toPersonId: 'ramona' },
        { type: 'parent_child', fromPersonId: 'susan', toPersonId: 'ramona' },
        { type: 'parent_child', fromPersonId: 'william', toPersonId: 'michaela' },
        { type: 'parent_child', fromPersonId: 'susan', toPersonId: 'michaela' },
        { type: 'parent_child', fromPersonId: 'william', toPersonId: 'aidan' },
        { type: 'parent_child', fromPersonId: 'susan', toPersonId: 'aidan' },

        // Seb & Valeria -> Enzo
        { type: 'parent_child', fromPersonId: 'seb', toPersonId: 'enzo' },
        { type: 'parent_child', fromPersonId: 'valeria', toPersonId: 'enzo' },

        // Alexander & Lauren -> Violet
        { type: 'parent_child', fromPersonId: 'alexander', toPersonId: 'violet' },
        { type: 'parent_child', fromPersonId: 'lauren', toPersonId: 'violet' }
    ]
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = FAMILY_DATA;
}
